import Footer from "@/components/Footer";
import "./globals.css";
import Nav from "@/components/Nav";
import { Poppins, Playfair_Display, Raleway } from "next/font/google";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const playfairDisplay = Playfair_Display({ weight: ['400', '500', '600', '700'], subsets: ["latin"], variable: '--playfair' });
const poppins = Poppins({ weight: ['400', '500', '600', '700'], subsets: ['latin'], variable: '--poppins' });
const raleway = Raleway({ weight: ['400', '500', '600', '700'], subsets: ["latin"], variable: '--raleway' });

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${poppins.className} ${playfairDisplay.className} ${raleway.className}`}>
      <body className={` antialiased`}>
        <Nav />
        {children}
        <Footer />
      </body>
    </html>
  );
}
